### ISSUE TITLE
Be Able to Define Cover Art File Name

### ISSUE THREAD

**Issue by chipbrownlee** [albertobeta/PodcastGenerator#217] opened 2020-02-09 03:58 UTC
Hi! I really love the Podcast Generator. It would be really helpful if you were able to define the file name of the iTunes cover art so that when you change the image it doesn't stay as "itunes_image.jpg". Some platforms, like Spotify, do not reload the cover art if the file name doesn't change.

On that note, does anyone have any advice for how I can manually change the name of the cover art in the feed?

**Comment by emilengler** [comment] 2020-02-09 09:26
> On that note, does anyone have any advice for how I can manually change the name of the cover art in the feed?

There is no comfortable way because everytime you regenerate your RSS feed it will be overwritten. However I am working on such a feature and it will get included into Version 3.1 which will be released in May this year (sorry for the waiting time :/)

I will close the issue now because it is a duplicate of #198

**Closed by emilengler** 2020-02-09 09:26 UTC
Labels: Duplicate, Feature Request
