### ISSUE TITLE
can it be my problem?

### ISSUE THREAD

**Issue by cacatuafm** [albertobeta/PodcastGenerator#162] opened 2019-12-31 16:25 UTC
I have this error, do not let go ... Good job, thanks. Happy New Year!!

Warning: sizeof(): Parameter must be an array or an object that implements Countable in /volume2/web/Podcast/themes/default/listepisodes.php on line 3

**Comment by emilengler** [comment] 2019-12-31 17:29
This error is normal. It should be gone when you add at least one episode

**Comment by cacatuafm** [comment] 2019-12-31 21:51
I got the error removed, uploading a file, but with a short name, just one word. and on the cover of the MP3, photographs embedded in file, it is not seen.

The load per ftp, well, but it only supports file name, a word, no dates, numbers, or separations, if you later want to edit it and add it in the name of the correct file it does not leave you, do not write the edition ... excuse the English, translate Google. Thanks for the answers.

**Comment by emilengler** [comment] 2020-01-01 01:08
> I got the error removed, uploading a file, but with a short name, just one word. and on the cover of the MP3, photographs embedded in file, it is not seen.

Oh this is not a bug, it's a feature!
You can disable this by editing `$strictfilenamepolicy` from `yes` to `no`

**Comment by emilengler** [comment] 2020-01-03 20:54
Is it fixed now?
Otherwise I would close this issue

**Comment by cacatuafm** [comment] 2020-01-03 21:19
yes, that fixed, I can put several words and numbers ... I have another error for me, I can not edit the files uploaded by ftp ... in description I can not write, nor save any changes .... I am still interested in project from you, thanks.

**Comment by emilengler** [comment] 2020-01-03 23:07
Maybe this is a permission problem.
Do you have shell access?
If so, could you do `ls -l media/` (In the Podcast Generator folder)

**Comment by cacatuafm** [comment] 2020-01-03 23:30
I have all the permissions in the middle folder and in everything ... it
does not let write, it is a Synology server ..























*"La información contenida en este mensaje y / o archivo (s) adjunto (s) es
confidencial / privilegiada y está destinada a ser leída solo por la (s)
persona (s) a la (s) que va dirigida. Si usted lee este mensaje y no es el
destinatario señalado, el empleado o el agente responsable de entregar el
mensaje al destinatario, o ha recibido esta comunicación por error, la
información que está totalmente prohibida y puede ser ilegal, cualquier
publicación, distribución o reproducción de esta comunicación y le rogamos
que nos notifique inmediatamente y nos devuelva el mensaje original a la
dirección arriba mencionada. No imprima este correo si no es necesario, así
protegemos el medio ambiente ".*

**Comment by cacatuafm** [comment] 2020-01-03 23:32
I have all the permissions in the middle folder and in everything ... it does not let write, it is a Synology server ...

**Comment by emilengler** [comment] 2020-01-04 08:17
Oh I see...
Could you post your value of your `$link` variable in your config.php?
Please set it to `?name=`

**Comment by cacatuafm** [comment] 2020-01-04 08:35
Hello, I do not want to disturb, I do not understand programming, I leave the project until it is more advanced, anyway I publish what you ask. very thankful.
$link = "$url."?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

**Comment by emilengler** [comment] 2020-01-04 08:48
Could you edit your config.php and change the line with link to

```
$link = "?name=";
```
This might help

**Comment by cacatuafm** [comment] 2020-01-04 08:52
Yes, I change it, I think it works now, I check and check ... just a moment

**Comment by cacatuafm** [comment] 2020-01-04 08:55
error information, still unable to edit files uploaded by FTP

Warning: main(): Cannot add element button number 1 when only 0 such elements exist in /volume2/web/Podcast/themes/default/singleepisode.php on line 23 Warning: main(): Cannot add element button number 1 when only 0 such elements exist in /volume2/web/Podcast/themes/default/singleepisode.php on line 23

**Comment by emilengler** [comment] 2020-01-04 09:24
Does it work?
This is just a warning not an error?

**Comment by cacatuafm** [comment] 2020-01-04 09:32
It does not work, you cannot edit the files uploaded by FTP

**Comment by cacatuafm** [comment] 2020-01-04 09:39
If you upload the files as a new episode, if the edition works, but with the FTP function, it does not work to edit category changes, it does not work to add more information

**Comment by emilengler** [comment] 2020-01-04 10:00
Strange, it works all fine for me o.O
could you please give me the output of `ls -l media/`?
I still believe this is a permission issue

**Comment by cacatuafm** [comment] 2020-01-05 04:04
hello, you can write, edit, files uploaded in ftp, just restart the server and the problem is solved. thanks

**Comment by emilengler** [comment] 2020-01-05 15:49
Ok, will close the issue then :)

**Closed by emilengler** 2020-01-05 15:49 UTC
