### ISSUE TITLE
Change deprecated constructors in classes to improve compatibility with later php versions

### ISSUE THREAD

**Issue by tech10** [albertobeta/PodcastGenerator#11] opened 2015-09-06 21:16 UTC
Whenever possible, it's probably a good idea to ensure a script doesn't generate these types of warnings. Also, when php versions change, it will make upgrading easier, especially if an end user is running on a host who stays fairly up to date with php code.

Here are some warnings I received during my testing with php 7 RC2.

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; StringReader has a deprecated constructor in /srv/www/public_html/podcastgen/components/php-gettext/streams.php on line 48

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; FileReader has a deprecated constructor in /srv/www/public_html/podcastgen/components/php-gettext/streams.php on line 84

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; CachedFileReader has a deprecated constructor in /srv/www/public_html/podcastgen/components/php-gettext/streams.php on line 145

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; gettext_reader has a deprecated constructor in /srv/www/public_html/podcastgen/components/php-gettext/gettext.php on line 36

**Comment by albertobeta** [comment] 2015-09-10 15:00
The latest stable version of PHP is 5.6.x, which is installed in the majority of web servers today. PG does not generate any deprecate error with it. PHP 7 is a pre release, and as soon as it will be officially available, the code will be update to ensure it will work properly and won't generate any error or notice. Which class generates that notice? (probably a 3rd party class). In general, feel free to fork the project and contribute to the code if you want to prepare PG for PHP7 (but be sure you ensure 100% retrocompatibility)

**Comment by tech10** [comment] 2015-09-10 21:33
Hi,
There were multiple classes that generated that warning, all part of the php-gettext package, which can be found on github [here.](https://github.com/smmoosavi/php-gettext)

According to PHP's manual, PHP 5.X uses the function __construct() in a class when an object is created, to set initial values and such. It shouldn't break backward compatibility to update the code now. I'll consider contributing, perhaps, though I'll need to read some docs and such first since it'll be my first time doing so.

Blake

**Comment by albertobeta** [comment] 2015-09-11 11:14
Great, thanks for pointing that out. As soon as new version of PHP become stable and start to be installed in production, I'll update 3rd parties components included in PG to ensure 100% with new versions.

**Comment by tech10** [comment] 2016-01-02 21:43
Hi,
Just thought I'd check on this. PHP7 has been stable for a while now, and was recently updated in the official extra packages for Arch Linux. At the moment, upgrading would stop Podcast Generator from working on the server on which I use it, as there's a few more things than the warnings which cause it to stop working properly. Any ETA for a version that works with PHP7?

Blake

**Comment by albertobeta** [comment] 2016-01-06 21:37
Hi, no ETA yet (I'll do my best but I'm extremely busy). In case you wish to contribute and fix those errors with PHP7 (while ensuring that PG is retro compatible with PHP5) I'll be more than glad to include the changes in the main branch.

**Comment by tech10** [comment] 2016-01-06 21:48
Hi,
Thanks for the reply, and I'll definitely keep it in mind.

Blake

**Comment by albertobeta** [comment] 2016-01-06 21:55
If you don't have time, I'll do as soon as I can. In case the errors are just deprecated notices due to the gettext third party library, they could be disabled in php.ini. However, if there are more important warnings that prevent PG to run properly, I'll have to solve them. The time consuming process will be ensuring retrocompatibility with PHP5 since, as soon as I release a new version of PG, it is also released in tens of thousand hosting servers running PHP5 through the control panels (PG is included Cpanel distributions through Softaculous), therefore I want to be extremely careful when I make changes to the core.

**Comment by tech10** [comment] 2016-01-06 21:56
Hi,
There was more than just warnings. I seem to recall a break statement being used where an exit statement could have been used, though I forget precisely where that was. There may also be other errors as well that I'm unaware of.

Blake

**Comment by albertobeta** [comment] 2016-02-28 09:51
Hi Blake,
I merged [your pull request](https://github.com/albertobeta/PodcastGenerator/pull/12), thanks for contributing. I've been testing PG with both PHP 5.6.10 and 7.0.0 and it works for me (i.e. I don't get any deprecated error when using the php-gettext package). Do you confirm that the issue is solved?

**Comment by tech10** [comment] 2016-02-28 12:43
Hi,
It was solved for me when I tested it, yes.

Blake

**Comment by albertobeta** [comment] 2016-02-28 13:06
Great, just [released the new version](https://github.com/albertobeta/PodcastGenerator/releases/tag/2.6).
Thank you for your contribution, much appreciated :+1:

**Closed** 2016-02-28 13:06 UTC
